services: 
  
  streamlit:
    image: streamlit_image
    build: 
      context: ./web_app
      dockerfile: Dockerfile
    ports:
      - 8501:8501
    volumes:
      - streamlit:/web_app/streamlit
      - ./data:/image_processing_pipeline/data
    #command: streamlit run /app/app.py
    environment:
      PROCESSED_FOLDER: /data/processed_images
      TO_PROCESS_FOLDER: /data/to_process_images
      MONGO_URL: mongodb://root:example@mongo:27017/
      MONGO_DB : prova_db
      MONGO_METADATA_COLLECTION : images_metadata
    networks:
      - shared_network

  #web_app:

networks:
  shared_network:
    external: true

volumes:
  streamlit: