services: 
  
  streamlit:
    image: streamlit_image
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 8501:8501
    volumes:
      - streamlit:/web_app/streamlit
    #command: streamlit run /app/app.py
    networks:
      - shared_network

  #web_app:

networks:
  shared_network:
    external: true

volumes:
  streamlit: